### ISSUE TITLE
`!search <anything>`, `!drc <anything>` fail with `TypeError: _request() got an unexpected keyword argument 'form'` on OS X

### ISSUE THREAD

**Issue by vorpal-buildbot** [PennyDreadfulMTG/Penny-Dreadful-Tools#9066]
Reported on Discord by bakert#2193

**Comment by bakert** [comment]
`git bisect` tells me that ff1fc7d9 is to blame.

**Comment by bakert** [comment]
prod mtgbot is running `071b310` and doesn't see the problem which can also be repro'ed on local with `!search anything`.

So I guess something about `pipenv run python dev.py build` is not sufficient to get local into a working state? But it works fine for jenkins and prod?

**Comment by bakert** [comment]
I found `    return self.request(r, form=form, files=files)` in `dpy_overrides.py` in `discord-py-slash-commands` which feels highly likely to be the monkeypatching culprit. So the inclusion of discord-py-slash-commands is the issue here? I don't understand why it doesn't afffect prod.

**Comment by bakert** [comment]
So, `discord-py-slash-commands` aka `discord-py-interactions` thinks it can send form as a kwarg to discord.py's http.send_files or at least its own override of said thing. But it cannot. I think. I still don't understand why current prod doesn't experience this issue.

**Comment by bakert** [comment]
Can actually repro with `!search` too.

**Comment by bakert** [comment]
This was an issue with my local dev env that I fixed.
